In [1]:
import numpy as np
import j
arra = np.array([3,3,3])
print(arra)

[3 3 3]


In [2]:
arra2 = np.ndarray([3,3,3])
print(arra2)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.29061074e-306 1.89146896e-307 7.56571288e-307]
  [3.11525958e-307 1.24610723e-306 1.37962320e-306]]

 [[1.29060871e-306 2.22518251e-306 1.33511969e-306]
  [1.78022342e-306 1.05700345e-307 1.11261027e-306]
  [1.11261502e-306 1.42410839e-306 7.56597770e-307]]

 [[6.23059726e-307 1.42419530e-306 1.37962185e-306]
  [1.37962049e-306 1.24610723e-306 1.60219035e-306]
  [9.34609790e-307 1.42410974e-306 1.63354242e-301]]]


2D array

In [3]:
arra_2 = np.array([[9,10,11,12],[[1,2,3,4],[5,6,7,8]]])
print(arra_2)

[list([9, 10, 11, 12]) list([[1, 2, 3, 4], [5, 6, 7, 8]])]


In [4]:
ex = np.zeros((2,2))
print(ex)

[[0. 0.]
 [0. 0.]]


In [5]:
ex = np.full((2,2),10)
print(ex)

[[10 10]
 [10 10]]


In [6]:
ex = np.eye(2,2)
print(ex)

[[1. 0.]
 [0. 1.]]


In [7]:
ex =np.ones((2,2))
print(ex)

[[1. 1.]
 [1. 1.]]


In [8]:
print(ex.shape)
print()
print(ex[0,1])

(2, 2)

1.0


# slicing of numpy array

In [9]:
new = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
view = new[2:,:3,:3]
print(view)

[]


In [10]:
new1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(new1[0])

[1 2 3]


In [11]:
print(new1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a_slice = np.array(new1)
print(a_slice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
col1 = a_slice[:,0]
print(col1)
col2 = a_slice [:,:1]
print(col2)


[1 4 7]
[[1]
 [4]
 [7]]


In [14]:
col2[1]=10
print(col2)

[[ 1]
 [10]
 [ 7]]


In [15]:
print(a_slice)

[[ 1  2  3]
 [10  5  6]
 [ 7  8  9]]


In [16]:
col2[1] = 4
print(a_slice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
col3 = a_slice[2:,:1]
print(col3)
print()
col3 = a_slice[:2, :1]
print(col3)

[[7]]

[[1]
 [4]]


In [18]:
an_array = np.array([[1,2,3,15],[5,6,7,16],[9,10,11,17],[12,13,14,18]])
print(an_array)

[[ 1  2  3 15]
 [ 5  6  7 16]
 [ 9 10 11 17]
 [12 13 14 18]]


In [19]:
row = np.arange(4)
col = np.array([0,1,2,3])

print(row)
print(col)

[0 1 2 3]
[0 1 2 3]


In [20]:
for row1,col1 in zip(row,col):
    print(row1,"," ,col1)

0 , 0
1 , 1
2 , 2
3 , 3


In [21]:
print(an_array[row,col])

[ 1  6 11 18]


# useful for datacleaning

In [22]:
an_array[row,col] +=100000
print(an_array)

[[100001      2      3     15]
 [     5 100006      7     16]
 [     9     10 100011     17]
 [    12     13     14 100018]]


# boolean array

In [23]:
an_array=np.array(([1,2,3],[4,5,6],[7,8,9]))
an_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
filter = (an_array>4)
print(filter)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [25]:
print(an_array[filter])

[5 6 7 8 9]


In [26]:
an_array[an_array %2 !=0] +=100
print(an_array)

[[101   2 103]
 [  4 105   6]
 [107   8 109]]


# Definig Data Type

In [27]:
ex1 = np.array([11,22,33])
print(ex1.dtype)

int32


In [28]:
ex2 = np.array([11.3,22.5],dtype=int)
print(ex2)

[11 22]


In [29]:
ex3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ex4 = np.array([[5,6,7,8],[1,2,3,4],[9,10,11,12]],dtype=np.float)
print(ex3)
print()
print(ex4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 5.  6.  7.  8.]
 [ 1.  2.  3.  4.]
 [ 9. 10. 11. 12.]]


In [30]:
print(np.add(ex3,ex4))

[[ 6.  8. 10. 12.]
 [ 6.  8. 10. 12.]
 [18. 20. 22. 24.]]


In [31]:
print(np.subtract(ex3,ex4))

[[-4. -4. -4. -4.]
 [ 4.  4.  4.  4.]
 [ 0.  0.  0.  0.]]


In [32]:
print(np.sqrt(ex3))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


In [33]:
print(np.sqrt(ex3,ex4))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


In [34]:
print(np.sqrt(ex4))

[[1.         1.18920712 1.31607401 1.41421356]
 [1.49534878 1.56508458 1.62657656 1.68179283]
 [1.73205081 1.77827941 1.82116029 1.86120972]]


In [35]:
print(np.sqrt(ex4))

[[1.         1.18920712 1.31607401 1.41421356]
 [1.49534878 1.56508458 1.62657656 1.68179283]
 [1.73205081 1.77827941 1.82116029 1.86120972]]


In [36]:
print(sum(ex4))

[6.23606798 7.02598097 7.69442691 8.29252874]


In [37]:
print(ex4.sum())

29.249004591697254


In [38]:
ex4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ex4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(ex4.mean())
print()
print(ex4.mean(axis=1))

5.0

[2. 5. 8.]


In [40]:
print(np.median(ex4,axis =1))

[2. 5. 8.]


# broadcasting

In [41]:
p1 = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(p1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
p2 = np.array([0,1,3])

In [43]:
y = p1+ p2
print(y)

[[ 1  3  6]
 [ 4  6  9]
 [ 7  9 12]]


In [44]:
cols = np.array([[5,6,7],[8,9,10],[11,12,13]])
cols = cols.T
print(cols)

[[ 5  8 11]
 [ 6  9 12]
 [ 7 10 13]]


In [45]:
x = p1 + cols
print(x)

[[ 6 10 14]
 [10 14 18]
 [14 18 22]]


# Using Dot operation

In [49]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b= np.array([[10,11,12],[13,14,15],[16,17,18]])
c=np.vdot(a,b)
print(c)

690


In [ ]:
import j